In [1]:
import numpy as np

# ndarrayの作成

python配列からnumpy配列を生成する。  
正確には配列LIKEなオブジェクトから生成可能。  

多次元配列を扱うことも可能。  
dtype引数では対象となる配列の要素のデータ型を指定する。  

<https://numpy.org/doc/stable/user/absolute_beginners.html>

In [2]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a)

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=np.float64)
print(a)

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 簡単な初期化メソッドあり。

In [14]:
zeros = np.zeros(2) # 1 row, 2 columns
print(zeros)

zeros = np.zeros((2, 3)) # 2 rows, 3 columns
print(zeros)

ones = np.ones(2) # 1 row 2 columns
print(ones)

ones = np.ones((2, 3)) # 2 rows, 3 columns
print(ones)

empties = np.empty(2) # 1 row, 2 columns
print(empties)

empties = np.empty((2, 3)) # 2 rows, 3 columns
print(empties)

arange = np.arange(2) # create an array with values from 0 to 2
print(arange)

arange = np.arange(2, 5) # create an array with values from 2 to 5
print(arange)

arange = np.arange(2, 5, 2) # create an array with values from 2 to 5 with step 2
print(arange)

[0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 1]
[2 3 4]
[2 4]
