In [1]:
import numpy as np

# ndarrayの作成

python配列からnumpy配列を生成する。  
正確には配列LIKEなオブジェクトから生成可能。  

多次元配列を扱うことも可能。  
dtype引数では対象となる配列の要素のデータ型を指定する。  

<https://numpy.org/doc/stable/user/absolute_beginners.html>

In [2]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a)

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=np.float64)
print(a)

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 簡単な初期化メソッドあり。

In [14]:
zeros = np.zeros(2) # 1 row, 2 columns
print(zeros)

zeros = np.zeros((2, 3)) # 2 rows, 3 columns
print(zeros)

ones = np.ones(2) # 1 row 2 columns
print(ones)

ones = np.ones((2, 3)) # 2 rows, 3 columns
print(ones)

empties = np.empty(2) # 1 row, 2 columns
print(empties)

empties = np.empty((2, 3)) # 2 rows, 3 columns
print(empties)

arange = np.arange(2) # create an array with values from 0 to 2
print(arange)

arange = np.arange(2, 5) # create an array with values from 2 to 5
print(arange)

arange = np.arange(2, 5, 2) # create an array with values from 2 to 5 with step 2
print(arange)

[0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 1]
[2 3 4]
[2 4]


# 要素へのアクセスは普通

In [15]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a[0]) # get the first element
print(a[1]) # get the second element
print(a[-1]) # get the last element
print(a[-2]) # get the second last element

1
2
10
9


# 多次元配列のそのまま

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a[0, 0]) # get the first element of the first row
print(a[0, 1]) # get the second element of the first row
print(a[0, 2]) # get the third element of the first row
print(a[1, 0]) # get the first element of the second row
print(a[1, 1]) # get the second element of the second row
print(a[1, 2]) # get the third element of the second row
print(a[2, 0]) # get the first element of the third row
print(a[2, 1]) # get the second element of the third row
print(a[2, 2]) # get the third element of the third row

1
2
3
4
5
6
7
8
9


# コロンを使用して範囲を指定できる

In [20]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a[0:2]) # get the first two elements

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[0, 0:2]) # get the first two elements of the first row
print(a[0:2, 0]) # get the first two elements of the first column

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[0:2, 0:2]) # get the first two rows and first two columns

[1 2]
[1 2]
[1 4]
[[1 2]
 [4 5]]


# 通常の演算子が使用可能

In [21]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(a + 1) # add 1 to each element
print(a - 1) # subtract 1 from each element
print(a * 2) # multiply each element by 2
print(a / 2) # divide each element by 2
print(a ** 2) # square each element

[ 2  3  4  5  6  7  8  9 10 11]
[0 1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18 20]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
[  1   4   9  16  25  36  49  64  81 100]


# 多次元配列でもOK!

In [22]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a + 1) # add 1 to each element
print(a - 1) # subtract 1 from each element
print(a * 2) # multiply each element by 2
print(a / 2) # divide each element by 2
print(a ** 2) # square each element

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


# 配列同士の演算

In [23]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = np.array([3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(a + b) # add two arrays
print(a - b) # subtract two arrays
print(a * b) # multiply two arrays
print(a / b) # divide two arrays
print(a ** b) # square two arrays

[ 4  6  8 10 12 14 16 18 20 22]
[-2 -2 -2 -2 -2 -2 -2 -2 -2 -2]
[  3   8  15  24  35  48  63  80  99 120]
[0.33333333 0.5        0.6        0.66666667 0.71428571 0.75
 0.77777778 0.8        0.81818182 0.83333333]
[            1            16           243          4096         78125
       1679616      40353607    1073741824   31381059609 1000000000000]
